name: InventoryTotem
version: '${project.version}'
main: fun.dungeonstudios.inventorytotem.InventoryTotem
api-version: '1.20'
authors: [Dungeon Studios]
description: Activate totems without having them in your off-hand
